# Generated by Django 5.2.1 on 2025-05-15 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['unique_code'], 'verbose_name_plural': 'Gym Members'},
        ),
    ]
