# Generated by Django 5.2.1 on 2025-05-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBMS', '0002_alter_membership_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=150)),
            ],
        ),
    ]
