# Generated by Django 5.2.1 on 2025-07-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBMS', '0002_remove_profile_dependant_user_otp_user_refresh_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['family_name'], 'verbose_name_plural': 'Students'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
